
apiVersion: v1
kind: Service
metadata:
  name: java-svc
  labels:
    name: java-svc
spec:
  type: NodePort
  ports:
    - targetPort: 8090
      port: 8090
      nodePort: 30008
  selector:
    app: java
    type: cd