
apiVersion: v1
kind: Service
metadata:
  name: java-svc2
  labels:
    name: java-svc2
spec:
  type: NodePort
  ports:
    - targetPort: 8090
      port: 8090
      nodePort: 30022
  selector:
    app: java
    type: cd
